### ISSUE TITLE
Project Scope

### ISSUE THREAD

**Issue by ivanb7** [ivanb7/soen341group3#7]
# Project scope

We will make a web communication platform for students and TAs. Users will be able to login with their Github account and have their repositories linked to their profile. Github statistics will be displayed on the user's profile. Users can create and join group chats. Users will be able to send private messages. Users will also be able to send files and documents.
Groups can be linked to github repositories, allowing to see statistics from github.

![16388773_10158157076615611_1303163316_o](https://cloud.githubusercontent.com/assets/16981596/22385838/63a54808-e4a2-11e6-9ac9-3bb1093ebbe3.jpg)
![16325416_10158157099390611_1282427289_o](https://cloud.githubusercontent.com/assets/16981596/22385840/65d6f0d6-e4a2-11e6-8c9d-f7d82d97f1d0.jpg)

**Comment by rena-21** [comment]
According to this website https://www.mountaingoatsoftware.com/agile/user-stories : the format of a user story should be:  "As a <type of user>, I want <some goal> so that <some reason>".

My proposition of **user stories**:
1. As a student,I want to be able to upload my assignment (i.e: programming assignment) to the right Ta.
2.As a Ta, I want to be able to give feedback and marks to the right student or the right group(i.e if it is a group project).

My suggestion for the setting up the website:
**Programming languages:** Javascript, 
Angular JS(front-end) 
Node.js (back-end)   
---> video explaining difference between angular.js and node.js https://www.youtube.com/watch?v=t7x7c-x90FU 

I am suggesting we can start from this simple **template** : http://www.w3schools.com/w3css/tryw3css_templates_social.htm

According to this website : https://www.slant.co/ we can search more easily. For instance, what is the best chat that we can use as api . I found this https://www.slant.co/topics/6813/~chat-software.

We need to think about which **database** to think : mySql or mongoDb 

For the team collaboration : we can use the  **Asana software** ----> https://asana.com/ it is basically a software to manage a project ( distribute the tasks and put deadline.) and also we can use github under the section projects if you click on it we can makes note, organize the work etc.

**Comment by ivanb7** [comment]
**User Stories:**

1. As a TA, I want to create groups that my students can join.
2. As a TA, I want to post group messages.
3. As a student, I want to send private messages.
4. As a user, I want to join multiple groups.
5. As a user, I want to login with my gitHub account
6. As a TA, I want to see how much a student has contibuted to a github project (number of commits).
7. As a user, I want to get a notification when I get a private or a group message.
8. As a user, I want to have the ability to modify which groups or people I get notification from, in my notification settings.

**Comment by YousefAboElFoul** [comment]
Format used: As a <type of user>, I want <some goal> so that <some reason>.
1.As a TA, I want to have easy access to students so that I can proceed to give immediate support.
2.As a TA, I want keep students posted so that everyone is on track.
3.As a student, I want to have documents of everything so that I am organized with my courses.
4.As a student, I want to organize conversations for every class so that I am always updated.
5.As a user, I want to be able to block people so that I don't get scammed.
6.As a user, I want to have privacy so that my account is not shared with everybody.

**Comment by nathan-shumm** [comment]
1.As a student, I want to message other students so that I can easily communicate with my classmates.
2.As a student, I want an indicator that shows a message has been seen so that I can assure the TA has viewed the message and there is no need for further contact until he has replied.

**Comment by Mateuse** [comment]
1. As a student, I want to be able to view previously asked questions made by my classmates to the TA, so that I can view common problems happening within the class. 
2. As a TA, I want to be able to select which questions can be viewed by everyone in the class, so that the rest of the class can take advantage of a solution to a common/difficult problem.

**Comment by mathiaco** [comment]
To implement our app we will need to use the github API. Here is a link for documentation that can help us.  
https://developer.github.com/v3/repos/contents/ 

Here are some user stories I propose:

1- As a TA, I want to be able to redirect my students to a timeline, so that I wil not have to answer the same questions multiple times.
2- As a student, I want to be able to post anonymously in groups, so that my github projects would not be displayed to everybody.
3- As a student,I want to be able to see all comments on a particular topic, so that I won't disturb my TA.

**Comment by jeffbuonamici** [comment]
1. As a student, I want to be able to access my group's conversation in order to converse about our group   project.
2. As a TA, I want access to many groups conversations in order to help and check up on students.
3. As a TA, I want to be able to create many groups called "Classes" to keep track of each class I teach.
4. As a user(TA and Student), I want access to a general class conversation, so that I can ask questions and     help others.

**Comment by I-Dream-Of-Machines** [comment]
1. As a student I want to be able to join multiple groups 
2. As student and as a TA I want to be able to link to a specific part of a GitHub repository in my group conversation.
